---
title: "First Knit"
author: "Daniel Flores"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended High School at a school called Browning in Long Beach California for my first two years then I moved to Palmdale and finished my last two years at Highland High School and I did graduate at Highland. For me english is easier than math because it's more about interpretation and expressing ideas, while math requires precise calculations with clear right or wrong answers.The subject I did the best in was art because it allowed me to be creative, express myself freely, and think outside the box without worrying about being wrong.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a apple computer specifically a Apple MacBook Air and on a scale of 1 to 10 I would rate myself a 7 as I already completed some courses online and also took a computer science course so I think I am well capable of working with a computer. My internet access at home is really good so I don't think I should run into any problems with the connection where i live.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I would like to be called Daniel.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
   What I want to achieve in life is to be able to be in a position to retire my mom and dad and also by them a house and just make sure my family doesn't ever have to worry about money ever again. The college subject that i think would interest me the most would be economics because it helps me understand opportunity costs and make better, more rational decisions in my daily life, such as financial investments, purchasing, and career choices. The degree i am trying to achieve is an AA degree in Economics then transition into getting my bachelors degree in Economics.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have gone to Mexico and the United Kingdom and both were very fun and brought unique experiences. I have not been in the military but if I were drafted I would join the Marine Corps and work something along the lines of Engineering and Maintenance as thats something that would interest me.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




